from __future__ import annotations

from dataclasses import dataclass

from .types import EpisodeInput, SupportDoc


FRESHNESS_BENCHMARK_SOURCE = "bundled_freshqa_style_snapshot_v1"


@dataclass(frozen=True, slots=True)
class FreshnessScenario:
    episode_id: str
    question: str
    gold_answer: str
    timestamp: int
    subject: str
    relation: str
    domain: str
    parametric_answer: str
    parametric_confidence: float
    recurrence_hint: float
    stability_hint: float
    volatility_hint: float
    contradiction_hint: float
    metadata: dict


def _doc(
    doc_id: str,
    text: str,
    answer: str,
    timestamp: int,
    trust: float,
    source: str = "freshness_snapshot",
) -> SupportDoc:
    return SupportDoc(
        doc_id=doc_id,
        text=text,
        answer=answer,
        source=source,
        timestamp=timestamp,
        trust=trust,
        relevance=0.0,
    )


def _episodes() -> list[FreshnessScenario]:
    return [
        FreshnessScenario(
            episode_id="probe-harbor-pre",
            question="What city hosts the Harbor AI Expo?",
            gold_answer="Seattle",
            timestamp=1,
            subject="Harbor AI Expo",
            relation="host_city",
            domain="events",
            parametric_answer="Seattle",
            parametric_confidence=0.97,
            recurrence_hint=0.15,
            stability_hint=0.95,
            volatility_hint=0.05,
            contradiction_hint=0.0,
            metadata={
                "update_id": "harbor-probe",
                "update_type": "forgetting_probe",
                "probe_group": "harbor_ai_expo",
                "probe_phase": "pre",
                "source_support_count": 0,
                "domain_change_rate": 0.02,
                "disable_retrieval": True,
                "stability_class": "stable",
                "volatility_class": "low",
            },
        ),
        FreshnessScenario(
            episode_id="acme-update-1",
            question="Who is the CEO of AcmeAI after the April 2025 board change?",
            gold_answer="Jordan Lee",
            timestamp=2,
            subject="AcmeAI",
            relation="ceo",
            domain="business",
            parametric_answer="Maya Chen",
            parametric_confidence=0.78,
            recurrence_hint=0.84,
            stability_hint=0.9,
            volatility_hint=0.16,
            contradiction_hint=0.22,
            metadata={
                "update_id": "acme-ceo",
                "update_type": "stable_update",
                "source_support_count": 2,
                "domain_change_rate": 0.25,
                "source_freshness": 1.0,
                "stability_class": "stable",
                "volatility_class": "low",
                "stale_answers": ["Maya Chen"],
                "temporary_patch_horizon": 1,
            },
        ),
        FreshnessScenario(
            episode_id="acme-confirm-1",
            question="Who leads AcmeAI now?",
            gold_answer="Jordan Lee",
            timestamp=3,
            subject="AcmeAI",
            relation="ceo",
            domain="business",
            parametric_answer="Maya Chen",
            parametric_confidence=0.74,
            recurrence_hint=0.9,
            stability_hint=0.93,
            volatility_hint=0.12,
            contradiction_hint=0.1,
            metadata={
                "update_id": "acme-ceo",
                "update_type": "confirmation",
                "source_support_count": 3,
                "domain_change_rate": 0.15,
                "source_freshness": 1.0,
                "stability_class": "stable",
                "volatility_class": "low",
                "stale_answers": ["Maya Chen"],
            },
        ),
        FreshnessScenario(
            episode_id="acme-confirm-2",
            question="Name AcmeAI's current CEO.",
            gold_answer="Jordan Lee",
            timestamp=4,
            subject="AcmeAI",
            relation="ceo",
            domain="business",
            parametric_answer="Maya Chen",
            parametric_confidence=0.72,
            recurrence_hint=0.92,
            stability_hint=0.95,
            volatility_hint=0.1,
            contradiction_hint=0.08,
            metadata={
                "update_id": "acme-ceo",
                "update_type": "confirmation",
                "source_support_count": 3,
                "domain_change_rate": 0.1,
                "source_freshness": 0.95,
                "stability_class": "stable",
                "volatility_class": "low",
                "stale_answers": ["Maya Chen"],
            },
        ),
        FreshnessScenario(
            episode_id="nova-update-1",
            question="What is NovaPhone's flash sale price today?",
            gold_answer="$699",
            timestamp=5,
            subject="NovaPhone",
            relation="sale_price",
            domain="retail",
            parametric_answer="$799",
            parametric_confidence=0.52,
            recurrence_hint=0.7,
            stability_hint=0.28,
            volatility_hint=0.95,
            contradiction_hint=0.35,
            metadata={
                "update_id": "nova-price",
                "update_type": "volatile_update",
                "source_support_count": 1,
                "domain_change_rate": 0.95,
                "source_freshness": 1.0,
                "stability_class": "volatile",
                "volatility_class": "high",
                "stale_answers": ["$799"],
                "temporary_patch_horizon": 1,
            },
        ),
        FreshnessScenario(
            episode_id="nova-update-2",
            question="What is NovaPhone's flash sale price this afternoon?",
            gold_answer="$749",
            timestamp=6,
            subject="NovaPhone",
            relation="sale_price",
            domain="retail",
            parametric_answer="$799",
            parametric_confidence=0.5,
            recurrence_hint=0.74,
            stability_hint=0.24,
            volatility_hint=0.98,
            contradiction_hint=0.42,
            metadata={
                "update_id": "nova-price",
                "update_type": "volatile_update",
                "source_support_count": 1,
                "domain_change_rate": 0.98,
                "source_freshness": 1.0,
                "stability_class": "volatile",
                "volatility_class": "high",
                "stale_answers": ["$699", "$799"],
                "temporary_patch_horizon": 1,
            },
        ),
        FreshnessScenario(
            episode_id="nova-update-3",
            question="What is NovaPhone's flash sale price this evening?",
            gold_answer="$729",
            timestamp=7,
            subject="NovaPhone",
            relation="sale_price",
            domain="retail",
            parametric_answer="$799",
            parametric_confidence=0.48,
            recurrence_hint=0.76,
            stability_hint=0.22,
            volatility_hint=0.99,
            contradiction_hint=0.45,
            metadata={
                "update_id": "nova-price",
                "update_type": "volatile_update",
                "source_support_count": 1,
                "domain_change_rate": 0.99,
                "source_freshness": 1.0,
                "stability_class": "volatile",
                "volatility_class": "high",
                "stale_answers": ["$699", "$749", "$799"],
                "temporary_patch_horizon": 1,
            },
        ),
        FreshnessScenario(
            episode_id="terra-update-1",
            question="Who is Terra Robotics' CFO after the 2025 restructuring?",
            gold_answer="Lina Gomez",
            timestamp=8,
            subject="Terra Robotics",
            relation="cfo",
            domain="business",
            parametric_answer="Victor Shaw",
            parametric_confidence=0.71,
            recurrence_hint=0.82,
            stability_hint=0.88,
            volatility_hint=0.18,
            contradiction_hint=0.16,
            metadata={
                "update_id": "terra-cfo",
                "update_type": "stable_update",
                "source_support_count": 2,
                "domain_change_rate": 0.2,
                "source_freshness": 1.0,
                "stability_class": "stable",
                "volatility_class": "low",
                "stale_answers": ["Victor Shaw"],
                "temporary_patch_horizon": 1,
            },
        ),
        FreshnessScenario(
            episode_id="terra-confirm-1",
            question="Who is the current Terra Robotics CFO?",
            gold_answer="Lina Gomez",
            timestamp=9,
            subject="Terra Robotics",
            relation="cfo",
            domain="business",
            parametric_answer="Victor Shaw",
            parametric_confidence=0.68,
            recurrence_hint=0.9,
            stability_hint=0.92,
            volatility_hint=0.12,
            contradiction_hint=0.08,
            metadata={
                "update_id": "terra-cfo",
                "update_type": "confirmation",
                "source_support_count": 3,
                "domain_change_rate": 0.1,
                "source_freshness": 0.96,
                "stability_class": "stable",
                "volatility_class": "low",
                "stale_answers": ["Victor Shaw"],
                "consolidation_candidate": True,
            },
        ),
        FreshnessScenario(
            episode_id="terra-rollback-1",
            question="Who is Terra Robotics' CFO after the filing correction?",
            gold_answer="Omar Nasser",
            timestamp=10,
            subject="Terra Robotics",
            relation="cfo",
            domain="business",
            parametric_answer="Victor Shaw",
            parametric_confidence=0.64,
            recurrence_hint=0.85,
            stability_hint=0.7,
            volatility_hint=0.45,
            contradiction_hint=0.58,
            metadata={
                "update_id": "terra-cfo-correction",
                "update_type": "rollback_probe",
                "source_support_count": 2,
                "domain_change_rate": 0.45,
                "source_freshness": 1.0,
                "stability_class": "corrective",
                "volatility_class": "medium",
                "rollback_probe": True,
                "stale_answers": ["Lina Gomez", "Victor Shaw"],
                "temporary_patch_horizon": 1,
            },
        ),
        FreshnessScenario(
            episode_id="terra-confirm-2",
            question="Who is Terra Robotics' CFO now?",
            gold_answer="Omar Nasser",
            timestamp=11,
            subject="Terra Robotics",
            relation="cfo",
            domain="business",
            parametric_answer="Victor Shaw",
            parametric_confidence=0.63,
            recurrence_hint=0.88,
            stability_hint=0.76,
            volatility_hint=0.28,
            contradiction_hint=0.22,
            metadata={
                "update_id": "terra-cfo-correction",
                "update_type": "confirmation",
                "source_support_count": 2,
                "domain_change_rate": 0.2,
                "source_freshness": 1.0,
                "stability_class": "stable",
                "volatility_class": "medium",
                "stale_answers": ["Lina Gomez", "Victor Shaw"],
            },
        ),
        FreshnessScenario(
            episode_id="redwood-update-1",
            question="Where will the Redwood Summit be held in 2026?",
            gold_answer="Denver",
            timestamp=12,
            subject="Redwood Summit",
            relation="host_city",
            domain="events",
            parametric_answer="Austin",
            parametric_confidence=0.61,
            recurrence_hint=0.79,
            stability_hint=0.86,
            volatility_hint=0.2,
            contradiction_hint=0.15,
            metadata={
                "update_id": "redwood-host",
                "update_type": "stable_update",
                "source_support_count": 2,
                "domain_change_rate": 0.18,
                "source_freshness": 1.0,
                "stability_class": "stable",
                "volatility_class": "low",
                "stale_answers": ["Austin"],
            },
        ),
        FreshnessScenario(
            episode_id="redwood-confirm-1",
            question="What city hosts the Redwood Summit now?",
            gold_answer="Denver",
            timestamp=13,
            subject="Redwood Summit",
            relation="host_city",
            domain="events",
            parametric_answer="Austin",
            parametric_confidence=0.6,
            recurrence_hint=0.88,
            stability_hint=0.9,
            volatility_hint=0.16,
            contradiction_hint=0.1,
            metadata={
                "update_id": "redwood-host",
                "update_type": "confirmation",
                "source_support_count": 3,
                "domain_change_rate": 0.12,
                "source_freshness": 1.0,
                "stability_class": "stable",
                "volatility_class": "low",
                "stale_answers": ["Austin"],
            },
        ),
        FreshnessScenario(
            episode_id="redwood-confirm-2",
            question="Where is the Redwood Summit held now?",
            gold_answer="Denver",
            timestamp=14,
            subject="Redwood Summit",
            relation="host_city",
            domain="events",
            parametric_answer="Austin",
            parametric_confidence=0.58,
            recurrence_hint=0.9,
            stability_hint=0.92,
            volatility_hint=0.14,
            contradiction_hint=0.08,
            metadata={
                "update_id": "redwood-host",
                "update_type": "confirmation",
                "source_support_count": 3,
                "domain_change_rate": 0.1,
                "source_freshness": 1.0,
                "stability_class": "stable",
                "volatility_class": "low",
                "stale_answers": ["Austin"],
            },
        ),
        FreshnessScenario(
            episode_id="probe-harbor-post",
            question="What city hosts the Harbor AI Expo?",
            gold_answer="Seattle",
            timestamp=15,
            subject="Harbor AI Expo",
            relation="host_city",
            domain="events",
            parametric_answer="Seattle",
            parametric_confidence=0.97,
            recurrence_hint=0.15,
            stability_hint=0.95,
            volatility_hint=0.05,
            contradiction_hint=0.0,
            metadata={
                "update_id": "harbor-probe",
                "update_type": "forgetting_probe",
                "probe_group": "harbor_ai_expo",
                "probe_phase": "post",
                "source_support_count": 0,
                "domain_change_rate": 0.02,
                "disable_retrieval": True,
                "stability_class": "stable",
                "volatility_class": "low",
            },
        ),
    ]


def _corpus() -> list[SupportDoc]:
    return [
        _doc("fresh:acme:old", "AcmeAI chief executive officer CEO Maya Chen led the company before the 2025 board change.", "Maya Chen", 1, 0.93),
        _doc("fresh:acme:new", "After the April 2025 board change, AcmeAI appointed Jordan Lee as chief executive officer CEO.", "Jordan Lee", 2, 0.84),
        _doc("fresh:acme:confirm", "Jordan Lee remains the CEO of AcmeAI according to the June 2025 investor letter.", "Jordan Lee", 3, 0.88),
        _doc("fresh:nova:morning", "NovaPhone flash sale price today is 699 dollars during the morning launch event.", "$699", 5, 0.78),
        _doc("fresh:nova:afternoon", "NovaPhone flash sale price this afternoon is 749 dollars according to the latest storefront update.", "$749", 6, 0.72),
        _doc("fresh:nova:evening", "NovaPhone flash sale price this evening is 729 dollars in the final update.", "$729", 7, 0.7),
        _doc("fresh:nova:stale", "NovaPhone standard sale price is 799 dollars according to the long-running product listing.", "$799", 4, 0.91),
        _doc("fresh:terra:old", "Terra Robotics chief financial officer CFO Victor Shaw served before the restructuring.", "Victor Shaw", 7, 0.9),
        _doc("fresh:terra:new", "After the 2025 restructuring, Terra Robotics named Lina Gomez as chief financial officer CFO.", "Lina Gomez", 8, 0.84),
        _doc("fresh:terra:confirm", "Terra Robotics confirmed Lina Gomez as CFO in the quarterly report.", "Lina Gomez", 9, 0.88),
        _doc("fresh:terra:correction", "Correction: Terra Robotics says Omar Nasser, not Lina Gomez, is the current CFO after the filing correction.", "Omar Nasser", 10, 0.89),
        _doc("fresh:redwood:old", "The Redwood Summit host city used to be Austin before the 2026 venue change.", "Austin", 11, 0.9),
        _doc("fresh:redwood:new", "For 2026, the Redwood Summit host city is Denver according to the planning memo.", "Denver", 12, 0.85),
        _doc("fresh:redwood:confirm", "The Redwood Summit remains scheduled for Denver in the updated event brief.", "Denver", 13, 0.89),
    ]


def build_freshness_benchmark(limit: int | None = None) -> tuple[list[EpisodeInput], list[SupportDoc], dict[str, str]]:
    scenarios = _episodes()
    if limit is not None and limit > 0:
        scenarios = scenarios[:limit]
    corpus_docs = _corpus()
    subject_doc_prefix = {
        "AcmeAI": "fresh:acme:",
        "NovaPhone": "fresh:nova:",
        "Terra Robotics": "fresh:terra:",
        "Redwood Summit": "fresh:redwood:",
        "Harbor AI Expo": "",
    }
    episodes: list[EpisodeInput] = []
    for scenario in scenarios:
        metadata = {
            "benchmark_source": FRESHNESS_BENCHMARK_SOURCE,
            **scenario.metadata,
        }
        prefix = subject_doc_prefix.get(scenario.subject, "")
        support_docs = [
            doc
            for doc in corpus_docs
            if prefix and doc.doc_id.startswith(prefix) and doc.timestamp <= scenario.timestamp
        ]
        episodes.append(
            EpisodeInput(
                episode_id=scenario.episode_id,
                question=scenario.question,
                gold_answer=scenario.gold_answer,
                dataset_id="freshness",
                timestamp=scenario.timestamp,
                subject=scenario.subject,
                relation=scenario.relation,
                domain=scenario.domain,
                support_docs=support_docs,
                parametric_answer=scenario.parametric_answer,
                parametric_confidence=scenario.parametric_confidence,
                popularity_bin=0.3,
                recurrence_hint=scenario.recurrence_hint,
                stability_hint=scenario.stability_hint,
                volatility_hint=scenario.volatility_hint,
                contradiction_hint=scenario.contradiction_hint,
                freshness=True,
                update_expected=scenario.metadata.get("update_type") != "forgetting_probe",
                metadata=metadata,
            )
        )
    manifest = {
        "benchmark_source": FRESHNESS_BENCHMARK_SOURCE,
        "episodes": str(len(episodes)),
        "corpus_docs": str(len(corpus_docs)),
    }
    return episodes, corpus_docs, manifest
